USE [master]
GO

/****** Object:  Database [SoN_Financeiro]    Script Date: 22/05/2019 23:18:39 ******/
CREATE DATABASE [SoN_Financeiro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SoN_Financeiro', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SoN_Financeiro.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SoN_Financeiro_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SoN_Financeiro_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SoN_Financeiro] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SoN_Financeiro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SoN_Financeiro] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET ARITHABORT OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SoN_Financeiro] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SoN_Financeiro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SoN_Financeiro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SoN_Financeiro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SoN_Financeiro] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SoN_Financeiro] SET  MULTI_USER 
GO

ALTER DATABASE [SoN_Financeiro] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SoN_Financeiro] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SoN_Financeiro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SoN_Financeiro] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SoN_Financeiro] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SoN_Financeiro] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SoN_Financeiro] SET  READ_WRITE 
GO

